# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

def common_pods
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxTest', '6.5.0'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'Kingfisher', '~> 7.2.1'
  pod 'Alamofire', '~> 5.6.0'
  pod 'Moya/RxSwift', '~> 15.0'
  pod 'RealmSwift', '~> 10.25.1'
  pod 'SwiftLint', '~> 0.47.0'
end

target 'Pokedex' do
  common_pods
  use_frameworks!

  # Pods for Pokedex

  target 'PokedexTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PokedexUITests' do
    # Pods for testing
  end

end
